package io.casehub.yaml.core.error;

public enum ErrorCategory {
    UNKNOWN_STEP, PARAMETER_VIOLATION, INVALID_STRUCTURE,
    EXPRESSION_PARSE, DUPLICATE_STEP,
    STEP_ACTION_FAILED, TIMEOUT, RETRY_EXHAUSTED, GUARD_REJECTED,
    EXPRESSION_EVAL,
    CHANNEL_CLOSED, DEADLINE_EXCEEDED, CORRELATION_TIMEOUT,
    SEMAPHORE_REENTRANCY, ILLEGAL_TRANSITION
}
